site_name: zet
repo_url: https://github.com/gsilvapt/zet
site_description: Public notes on various topics
site_author: gsilvapt
nav:
  - Home: index.md
  - Archive: zet/index.md
theme: 
  name: mkdocs
  user_color_mode_toggle: true
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  include_sidebar: false

markdown_extensions:
  - footnotes
  - toc:
      permalink: "#"


